FROM oven/bun:1.3.14

WORKDIR /app

# Copy dependency files terlebih dahulu agar Docker layer dapat di-cache
COPY package.json bun.lock ./

# Development membutuhkan dependencies dan devDependencies
RUN bun install --frozen-lockfile

# Copy seluruh project
COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]